id: medcom.ehmi.dk.terminology
canonical: http://medcomehmi.dk/ig/terminology
name: DK EHMI Terminology IG
title: "DK EHMI Terminology"
description: The DK EHMI Terminology IG
status: draft # draft | active | retired | unknown
version: 1.0.0-draft
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
jurisdiction: urn:iso:std:iso:3166#DK "Denmark"
publisher:
  name: MedCom
  url: http://medcom.dk
  email: ehmi@medcom.dk

dependencies:
  ihe.iti.balp: 1.1.3
  ihe.iti.mcsd: 4.0.0
  hl7.fhir.dk.core: 3.4.0

menu:
  Home: index.html
  Terminology: terminology.html
  More:
    Table of Contents: toc.html
    Downloads: downloads.html
    Dependencies: dependencies.html

parameters:
  apply-version: false
  default-version: true
  apply-publisher: false
  default-publisher: true
  pin-canonicals: pin-multiples
  excludettl: true